# Generated by Django 5.0.1 on 2024-01-19 04:16

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[500, 500],
                upload_to="image/%Y/%m",
            ),
        ),
    ]
