# Generated by Django 5.0.1 on 2024-04-17 11:01

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                default=0,
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[500, 500],
                upload_to="profile",
            ),
            preserve_default=False,
        ),
    ]
